<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;
use Laravel\Socialite\Facades\Socialite;

class SocialLoginController extends Controller
{

    public function redirect(): RedirectResponse
    {
        return Socialite::driver('github')->redirect();
    }

    public function callback(): RedirectResponse
    {
        $user = Socialite::driver('github')->user();
        $githubUser = User::updateOrCreate([
            'github_id' => $user->id
         ], [
            'name' => $user->name,
            'email' => $user->email,
            'password' => bcrypt(request(Str::random())) // Set some random password
            ]);

        // Log in the new or updated user.
        auth()->login($githubUser, true);

        // Redirect to url as requested by user, if empty use /dashboard page as generated by Jetstream
        return redirect()->intended('/dashboard');
    }


    // public function toProvider($driver)
    // {
    //     return Socialite::driver($driver)->redirect();
    // }

    // public function handleCallback($driver)
    // {
    //     $user = Socialite::driver($driver)->user();
    //     $user_account  = SocialLogin::where('provider', $driver)->where('provider_id', $user->id)->first();
    //     if ($user_account) {
    //         Auth::login($user_account->user);
    //         Session::regenerate();
    //         return redirect()->intended('admin.dashboard');
    //     }
    //     else{
    //         $db_user = User::where('email', $user->email)->first();
    //         if ($db_user) {
    //             SocialLogin::create([
    //                 'provider' => $driver,
    //                 "provider_id" => $user->id,
    //                 "user_id" => $db_user->id,
    //             ]);
    //         }else{
    //             $db_user = User::create([
    //                 'name' => $user->getName(),
    //                 'email' => $user->getEmail(),
    //                 'password' => bcrypt(rand(1000,9999)),
    //             ]);
    //         }
    //         Auth::login($db_user);
    //         Session::regenerate();
    //         return redirect()->intended('dashboard');
    //     }
    // }
}
